version: "3.8"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tryphysx_devcontainer
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
  ngrok:
    image: ngrok/ngrok:3
    container_name: tryphysx_ngrok
    command:
      - "http"
      - "http://host.docker.internal:54162"
    ports:
      - 4040:4040
    env_file:
      - ../.env
